instance:
  hostname: localhost

client:
  service-url:
    defaultZone: http://localhost:8761/eureka

server:
  port: 8078

spring:
  application:
    name: friend-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social-networks
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: false

    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        permittedNumberOfCallsInHalfOpenState: 4
        waitDurationInOpenState: 10000


      management:
        tracing:
          sampling:
            probability: 1.0


