server:
  port: 8074

spring:
  application:
    name: post-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  # Configurations spécifiques à Kafka

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:com.nabilaitnacer.servicepost.event.PostPlacedEvent
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        permittedNumberOfCallsInHalfOpenState: 4
        waitDurationInOpenState: 10000

management:
  tracing:
    sampling:
      probability: 1.0

