eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8016
spring:
  application:
    name: social-media-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mediadb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
      file-size-threshold: 2KB

file:
  upload-dir: /Users/kawtarmahy/Desktop/gc/social-network-microservice/images/

management:
  tracing:
    sampling:
      probability: 1.0
